### ISSUE TITLE
python3脚本

### ISSUE THREAD

**Issue by WCX1024979076** [mrwtong/AutoLogin_Mail#1]
此脚本不适用于python3，能否开发一下？

**Comment by mrwtong** [comment]
最近比较忙，等这一阵过了吧，其实改几个地方就可以了

**Comment by WCX1024979076** [comment]
好的

**Comment by WCX1024979076** [comment]
`import requests
import os
import time,json
from urllib import request
USERNAME = '学号'
PASSWORD = '数字石大密码'
SERVICE = r'defalut'
CAPTIVE_SERVER = r'http://www.baidu.com'

def login():
    url='http://www.dianping.com'
    header={
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36"
    }
    req=request.Request(url,headers=header)
    res=request.urlopen(req)
    login_page_url = res.geturl()
    login_url = login_page_url.split('?')[0].replace('index.jsp', 'InterFace.do?method=login')
    query_string = login_page_url.split('?')[1]
    query_string = query_string.replace('&', '%2526')
    query_string = query_string.replace('=', '%253D')
    headers = {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'Connection': 'keep-alive',
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36'
    }
    login_post_data = 'userId={}&password={}&service={}&queryString={}&operatorPwd=&operatorUserId=&validcode=&passwordEncrypt=false'.format(
        USERNAME, PASSWORD, SERVICE, query_string)
    login_result = requests.post(
        url=login_url,
        data=login_post_data,
        headers=headers
    )
    print(login_result.content.decode('utf-8'))


if __name__ == '__main__':
    message=os.system("netsh wlan connect name=UPC")
    print(message)
    time.sleep(5)
    try:
        login()
    except:
        print("用户已连接")
input("请按任意键继续")`
这是我借鉴别人写的代码，自己稍稍更改了一下。

**Comment by WCX1024979076** [comment]
这是我借鉴别人写的自动连接脚本并略作修改，可以参考一下。
https://paste.ubuntu.com/p/mtXMG2zWGv/

**Comment by mrwtong** [comment]
好的，谢谢~

**Comment by mrwtong** [comment]
已修改，现在使用python3运行，python2不再支持了

**Comment by mrwtong** [comment]
已修改，现在使用python3运行，python2不再支持了
